version: '3'
services:
  camping-js-ms:
    build: ./camping-js-ms
    ports:
      - "3000:3000"
    links:
      - mongodb
    depends_on:
      - mongodb
    networks:
      - mynetwork

  mongodb:
    image: mongo:latest
    ports:
      - "27018:27017"
    networks:
      - mynetwork
  
  keycloak:
    image: jboss/keycloak
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
    ports:
      - "8086:8080"
  

networks:
  mynetwork: